# Generated by Django 4.2.6 on 2023-10-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduTernApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.IntegerField()),
            ],
        ),
    ]
