# Generated by Django 4.2.6 on 2023-10-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduTernApp', '0002_regdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('courseId', models.AutoField(primary_key=True, serialize=False)),
                ('courseTitle', models.CharField(max_length=1000)),
                ('courseObjectives', models.TextField()),
                ('courseOverview', models.TextField()),
                ('courseRequirements', models.TextField()),
                ('courseDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CoursePricing',
            fields=[
                ('coursePricingId', models.AutoField(primary_key=True, serialize=False)),
                ('courseTitle', models.TextField()),
                ('originalCost', models.IntegerField()),
                ('discountPercentage', models.FloatField()),
                ('discountedPrice', models.FloatField()),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduTernApp.coursedetails')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationInfo',
            fields=[
                ('registrationInfoId', models.AutoField(primary_key=True, serialize=False)),
                ('courseEnrolled', models.TextField()),
                ('paymentDate', models.DateField()),
                ('paymentTransactionId', models.TextField()),
                ('ammountPaid', models.IntegerField()),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduTernApp.coursedetails')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=1000)),
                ('studentEmail', models.CharField(max_length=1000)),
                ('studentPassword', models.CharField(max_length=1000)),
                ('studentDOB', models.DateField()),
                ('studentPhoneNumber', models.CharField(max_length=12)),
                ('collegeName', models.TextField()),
                ('fieldOfStudy', models.TextField()),
                ('yearOfStudy', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='RegDetails',
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='email',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='password',
            field=models.CharField(max_length=1000),
        ),
        migrations.AddField(
            model_name='registrationinfo',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduTernApp.studentinformation'),
        ),
    ]
