# Generated by Django 4.2.6 on 2023-10-27 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduTernApp', '0003_coursedetails_coursepricing_registrationinfo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentDetail',
        ),
    ]
