# Generated by Django 4.2.6 on 2023-10-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduTernApp', '0004_delete_studentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
            ],
        ),
    ]
