# Generated by Django 4.2.6 on 2023-10-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduTernApp', '0005_studentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='studentDOB',
            field=models.DateField(null=True),
        ),
    ]
